### ISSUE TITLE
[bug] Doesn't work with sveltekit `immutable` flag

### ISSUE THREAD

**Issue by acurrieclark** [simeydotme/svelte-range-slider-pips#101]
When Sveltekit has the `immutable` compiler flag enabled, the slider does not move or update.

Using: 
```svelte
<svelte:options immutable={true} />
```
in a component does not have the same effect, and the slider updates as expected.

**To Reproduce**
I have created a minimal reproduction here:
https://www.sveltelab.dev/erqv5qgq8y33hg6

1. Load the REPL above. Attempt to slide the slider.
2. Set `immutable` to `false` in `svelte.config.js`
3. Observe that the slider now works as expected

**Expected behavior**
The slider should update regardless of the immutable setting.

**Comment by acurrieclark** [comment]
Did a little digging into this myself, then discovered that someone has already submitted a PR to resolve the issue. This is fixed in #21.

The other solution to the problem would be to add set the immutable flag to false locally by adding:

```svelte
<svelte:options immutable={false} />
```

to the top of `RangeSlider.svelte`. Either the current PR or that solution fixes the issue in my local tests.

**Comment by simeydotme** [comment]
thanks @acurrieclark  ... gosh I forgot about this,
I like your solution a bit more than the other one, as it means I don't need to test every possible scenario... the solution in #21 was taxing on me due to it having possible side effects.

Do you want to submit this as a PR and I'll merge it?

**Comment by acurrieclark** [comment]
No problem. PR at #103

**Comment by simeydotme** [comment]
Resolved
