### ISSUE TITLE
Slider won't appear inside of the nested component

### ISSUE THREAD

**Issue by serferdinand2** [simeydotme/svelte-range-slider-pips#102]
**Describe the bug**
When used inside of a component id renders as a non-movable knob. While if rendered on the page independent of  any component, it renders fine.

**To Reproduce**

in SvelteKit in +page.svelte import Question.svelte and RangeSlider

<RangeSlider/>

<Question {props}/>

in Question.svelte import Range.svelte 

<Range {props.options}/>

In Range.svelte import RangeSlider and use it in the HTML section as 

<RangeSlider />

When the page is loaded in the browser the slider that is on the page will show and the one that is inside of the Question element will be just a 

![Screenshot 2023-05-25 at 22 31 14](https://github.com/simeydotme/svelte-range-slider-pips/assets/93290291/ceabfd7a-ab4e-4eb9-8b89-c6e341ff9edb)

![Screenshot 2023-05-25 at 22 30 20](https://github.com/simeydotme/svelte-range-slider-pips/assets/93290291/e10b3cbe-2b0c-4f4e-a3c0-bedff6838b1c)

**Device/Environment**

Sveltekit, Vite, MacOS, Chromium/Edge/Chrome

e.

**Comment by simeydotme** [comment]
Hi @serferdinand2  I appreciate your issue raised :) thanks, and sorry you are having problems!
Would you be able to re-create this issue in CodeSandbox, or StackBlitz, please so I can see the error and download the code for debugging.

Thanks
