### ISSUE TITLE
[feature] A11y label

### ISSUE THREAD

**Issue by sawyerclick** [simeydotme/svelte-range-slider-pips#104]
**Describe the feature**
Add an ability for users to label the slider via `aria-label`, `aria-labelledby`, `aria-describedby`. An accessible name is required for this to be a true replacement for `<input type='range'/>`.

**Explain it's value / reasoning**
Simple in-line labeling with minimal refactor. This creates an explicit label opposed to any implicit association by wrapping the text or otherwise

**Additional context**
See labelling section on MDN: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/slider_role#the_slider_role_compared_other_range_options

**Comment by simeydotme** [comment]
Thanks @sawyerclick , is this the same as #93 ?

**Comment by sawyerclick** [comment]
ah, it precisely is. sorry for the repetition! will close in favor of that one
