### ISSUE TITLE
Question: How do I bind to a value from a writable store?

### ISSUE THREAD

**Issue by rchrdnsh** [simeydotme/svelte-range-slider-pips#11]
I am trying out your slider in a REPL:

https://svelte.dev/repl/9e6d515b510143e4b1b8a7a01940f0db?version=3.29.6

...where I am trying to use it as a volume slider that is bound to the volume output of the Howler JS Audio library.

At line 40 in the `Player.svelte` file I have a range input that is bound to the `$volume` of a store and it works as advertised.

I cannot figure out how to bind that same value to the instance of your slider at line 43 underneath it.

I have the native range commented out and am trying to pass the `$volume` from the `player-lib.js` file but can't make it work, so not sure how to go about making it work :-)

**Comment by simeydotme** [comment]
Hi @rchrdnsh 

I think this is more of a Svelte question, but it seems you'll need to store the volume as an Array in the store, after I tried that in your demo it works well. I assume at some point you need that value to pass in to Howler, so you may use a filter, or `[0]` to get the value from that array (which should also be reactive)

Cheers
