### ISSUE TITLE
[improvement] ARIA role warning about wrapping div

### ISSUE THREAD

**Issue by markjaquith** [simeydotme/svelte-range-slider-pips#112]
The latest ARIA change are a big improvement, but one more thing is still outstanding.

**Describe the bug**
> vite v4.4.9 building SSR bundle for production...
transforming (205) src/lib/svg/Pins.svelte11:47:05 AM [vite-plugin-svelte] /my/path/node_modules/svelte-range-slider-pips/src/RangeSlider.svelte:786:0 A11y: <div> with mousedown, mouseup handlers must have an ARIA role
> 784: </style>
> 785:
> 786: <div
>     ^
> 787:   {id}
> 788:   bind:this={slider}

**To Reproduce**

`<RangeSlider ... />` 2.2.2 and Svelte 4.1.2

- ⛔ **Fork [this REPL as a reduced test case](https://svelte.dev/repl/030797781fd64ad88302d1343f5b2c43?version=3.32.1)** for any bug/issue submissions!

https://svelte.dev/repl/030797781fd64ad88302d1343f5b2c43?version=4.1.2

(Warning immediately available)

**Comment by simeydotme** [comment]
yeh I noticed this, thanks, I think it was a change in svelte-core which caused this to being happening.
I'll look into it, but likely I will just put another ignore clause in there

**Comment by jackson-jackson** [comment]
Any progress on this? 👀

**Comment by simeydotme** [comment]
it's not really high priority since it's just a warning in Dev mode ...

**Comment by simeydotme** [comment]
ergh ... ofcourse .. i'd need to upgrade to v4 to get this warning ... and then rollup stops working, so i'll need to upgrade to vite bundler ... :'(

**Comment by jackson-jackson** [comment]
Isn't open source wonderful? 🤣

**Comment by simeydotme** [comment]
urgh, low priority ... 

I can't test it without massive overhaul to the repo, I think ... and I literally have no idea how to build a standalone svelte component in sveltekit compiled into UMD/ESM, that shit is maddening! there needs to be some kind of recipe for it. (if there is, sorry, but i cant find one)

i'll work on this when I have a whole weekend to bang my head
