### ISSUE TITLE
Multiple subscription updates when binding to store

### ISSUE THREAD

**Issue by mivermeu** [simeydotme/svelte-range-slider-pips#116]
**Describe the bug**
When binding the RangeSlider to a store or an element of a store, subscriptions to that store unexpectedly fire multiple times depending on how many RangeSliders are bound to that store.

**To Reproduce**

[REPL](https://svelte.dev/repl/bfd4f757bfde45d1a61adb285289266b?version=4.2.0)

1. Go to the REPL.
2. Click on any of the RangeSlider bars to change the value of the store they are bound to, or alter the value in the text input field.
3. Observe the number of subscription updates per change in the console logs.

**Expected behavior**
I would expect the number of subscription updates to be 1 per change and independent of the number of other sliders attached to the same store. In the same REPL used to reproduce the bug, native HTML sliders are present that align better with the expected behaviour.

**Additional context**
I've been using this component in my first Svelte project and it's worked great so far! Since I'm new to Svelte hopefully I didn't mistake intended behaviour for a bug.

In my use-case, I use a Svelte store to keep track of a number of parameters, with a `RangeSlider` controlling the value of each. A lot of calculations need to take place when one parameter in the store changes, so it's important that the subscription doesn't fire more than once per parameter change. The REPL used in this report binds multiple RangeSliders to the same element in a store, which reproduces the bug in a simpler way.

**Comment by simeydotme** [comment]
Thanks for the lovely issue, and REPL!
I'll check it out.
