### ISSUE TITLE
Argument of type 'typeof RangeSlider' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.

### ISSUE THREAD

**Issue by internpoon** [simeydotme/svelte-range-slider-pips#121]
**Describe the bug**
Argument of type 'typeof RangeSlider' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.   Types of construct signatures are incompatible. Type 'new (options: any) => RangeSlider' is not assignable to type 'new (args: { target: any; props?: any; }) => ATypedSvelteComponent'.       Type 'RangeSlider' is missing the following properties from type 'ATypedSvelteComponent': $$prop_def, $$events_def, $$slot_def

**To Reproduce**

- ⛔ **Fork [this REPL as a reduced test case](https://svelte.dev/repl/030797781fd64ad88302d1343f5b2c43?version=3.32.1)** for any bug/issue submissions!

**Expected behavior**
Trying to do a filter range slider and i got this, not sure how to resolve

**Screenshots**
![CleanShot 2023-11-17 at 16 44 53@2x](https://github.com/simeydotme/svelte-range-slider-pips/assets/21053694/034728fb-0f06-4878-af3e-b996f870e21a)

**Device/Environtment**
Please describe the environment and device the bug was found on, if relevant.

**Additional context**

**Comment by simeydotme** [comment]
delete TypeScript
