### ISSUE TITLE
Latest version breaks SSR due to use of document inside pureText

### ISSUE THREAD

**Issue by enyo** [simeydotme/svelte-range-slider-pips#131]
**Describe the bug**

Latest version breaks SSR due to use of document inside pureText

**To Reproduce**

SSR any page that uses svelte-range-slider

**Expected behavior**

Should handle SSR gracefully

**Comment by simeydotme** [comment]
ah shit, thanks
I need to set up a proper test with SvelteKit, I guess

**Comment by simeydotme** [comment]
I thought using the built-in DOM tools was safer, but I'll just revert to using a `regex`, then

```js
  return possibleHtml.replace(/<[^>]*>/g, '');
  ```
  
  will fix this asap
