### ISSUE TITLE
preventDefault on the click event

### ISSUE THREAD

**Issue by mquandalle** [simeydotme/svelte-range-slider-pips#14]
Hello,

Thank you very much for this very well designed component !

I have an issue with its integration inside a "popover" UI component. I have an event handler that close the "popover" when we click outside of it : https://svelte.dev/repl/802bb20faafc4256a0abc0afcba4cd46?version=3.31.0. In the REPL, if you start the interaction by clicking on the slider and finish it outside of the popover, the popover will be immediately closed wich is not what we want here.

The technical solution would be to call `event.preventDefault` in the slider handler, but I'm not sure how to do that. Maybe it could also be called by default? (not sure of the implications?

**Comment by simeydotme** [comment]
Hi @mquandalle 

I've just checked the REPL you linked on my mobile and it seems to function as you described. I'm guessing it's a mouse only problem?

May you confirm my findings, and I'll investigate the mouse issue when I get a chance :)

**Comment by mquandalle** [comment]
Yes, I didn't realize that but it works on mobile indeed.

**Comment by simeydotme** [comment]
hi @mquandalle 

https://svelte.dev/repl/337a4238f0774b56be2ed960c5b3553f?version=3.31.0

See this REPL with a solution, it is not really the Slider's fault, and I don't think changing any of the slider code will help considering you were looking at a `click` event which is never fired by the Slider.

However the solution I share is simply checking if the `mousedown` started inside of the popover, and if not then it can close safely. I would say, though, that there appears to be some double-firing of your `mouseup` event which may be a problem, and also seems you have no catering for touch device.
