### ISSUE TITLE
[bug] Mouse interactions are misaligned if slider is inside iframe.

### ISSUE THREAD

**Issue by thinkexec** [simeydotme/svelte-range-slider-pips#143]
**Describe the bug**
When slider is housed inside an iframe that is offset from the window (0,0) position, it is impossible to correctly use it. Starting to 
 drag the slider with the mouse works fine (the ball can be picked up where it's visible). To actually set a value though mouse has to be moved to area where iframe would be if it was placed at (0,0) in the window.

**To Reproduce**

- ⛔ **Fork [this REPL as a reduced test case](https://svelte.dev/repl/030797781fd64ad88302d1343f5b2c43?version=3.32.1)** for any bug/issue submissions!

**Expected behavior**
I would like the slider to know it's actual position not based on the window(?). 
Should there be an option to pass parent element?

**Screenshots**
![image](https://github.com/simeydotme/svelte-range-slider-pips/assets/103140342/0dd20055-a396-430c-b0d5-65b1fdd0894e)

**Device/Environment**
Please describe the environment and device the bug was found on, if relevant.

**Additional context**

**Comment by simeydotme** [comment]
thanks for the detailed bug report!
appreciate that and will investigate asap

**Comment by simeydotme** [comment]
oh do you think you could use the REPL to reproduce the issue for me?

**Comment by thinkexec** [comment]
Yeah just debugged REPL and indeed it is using iframe.
Wonder if there is some workaround or override in REPL done under the hood to make that iframe super isolated?
Something I failed to do in the project I am working on (and unfortunately can't just share it :( )

For now in that project I just reverted to using plain <input type="range".../> and it is handling the position just fine out of the box.

**Comment by simeydotme** [comment]
> Yeah just debugged REPL and indeed it is using iframe. Wonder if there is some workaround or override in REPL done under the hood to make that iframe super isolated?

not sure, are you using any special positioning or transforms on the iFrame? I would imagine something since I can see it's working more like a traditional frameset (whole height, right-side). Is it in a grid, or flexbox ?
