### ISSUE TITLE
[bug] RangeSlider doesn't work with immutable: true svelte setting

### ISSUE THREAD

**Issue by nielk** [simeydotme/svelte-range-slider-pips#146]
**Describe the bug**
In the context of a svelte config with `immutable: true`, the range slider does not work since the 3.0.0 release.

**To Reproduce**

- [stackblitz](https://stackblitz.com/edit/vitejs-vite-rwfqjn?file=svelte.config.js)

- Go to the bug reproduction here: [stackblitz](https://stackblitz.com/edit/vitejs-vite-rwfqjn?file=svelte.config.js)
- Try to interact with the slider (it does not move on click or drag)
- In `svelte.config.js` change the value of `immutable` to `false`, now it works as expected.

**Expected behavior**
The slider should update regardless of the immutable setting.

**Additional context**
It seems similar to https://github.com/simeydotme/svelte-range-slider-pips/issues/101

**Comment by simeydotme** [comment]
published 3.1.1
