### ISSUE TITLE
bounded percentage range slider

### ISSUE THREAD

**Issue by shedali** [simeydotme/svelte-range-slider-pips#19]
is it possible to have a min range slider to represent 0 to 100 percent, but enable sliding between a bounded range within the min/max range? 

I am looking for a way to link multiple percentage sliders to add up to 100

**Comment by shedali** [comment]
update: am able to simulate this by hiding one of the handles on the range input which achieves the desired effect

https://svelte.dev/repl/e431496fef524a74b5744126be1527f6?version=3.31.2

**Comment by simeydotme** [comment]
I would say that you just need to create a new DIV (background), and then place the range slider on top (position: absolute) with the min/max set to your bounds ... depending on your design, you may need to add your own pips/notches for the background, too... 

I can't help much more than that without knowing your requirements (design/func), but at this point I also do not think that this is a important or common feature that would be valuable code addition. Happy for people to add +1's and see how popular/requested it is.

If you're comfortable/confident with Svelte, you can always make a wrapper-component which does the thing above which I described :)

**Comment by simeydotme** [comment]
do you mean something like this: https://svelte.dev/repl/8db6358c61ce4b349c9380469db89b15?version=3.31.2 , @shedali  ?

**Comment by shedali** [comment]
This might not be the appropriate use for a range component, but what I had in mind was something like this

(hidden second pushy)
https://svelte.dev/repl/e431496fef524a74b5744126be1527f6?version=3.31.2

or

additional upperBound prop
https://svelte.dev/repl/d18e2e50e43449ad8b48533ed6b1efc9?version=3.31.2

My specific use case is for an array of range sliders, all representing a proportion of 100%.

This is probably quite niche so happy to close, can perhaps reopen if there is enough additional interest
