### ISSUE TITLE
Bug: Setting min and max to zero when component first loads prevents slider ball from moving

### ISSUE THREAD

**Issue by JustinHawtree** [simeydotme/svelte-range-slider-pips#20]
So for the past couple hours I have been trying to narrow this bug down to make it reproducible. The exact bug is when the slider starts off at min=0 and max=0, then dynamically changing max prop with a variable to a high number (I.E. 100) the slider ball will stay at the beginning position (not moving to the right) but the value (float prop) above the ball will change when I try to move the slider ball. I looked at the css and it shows left: NaN%. Surprising, If I make max -1 first and then change the max variable like the previous example, the slider ball will move like normal.

Environment: Svelte 3.0

How to reproduce:
Create a max variable and set it to 0
Set slider component props min=0 and max={ max_var }
Then change max_var to 100
Try to slide the slider ball and it will stay in the beginning (initial) position, but the values variable value will update

**Comment by simeydotme** [comment]
I see...
https://svelte.dev/repl/0628aed7efe34e719027fb751fa4f6a3?version=3.32.1
there's a reduced case.

Looks weird, but also I'm not sure if I would say `min` + `max` set to `0` is a valid scenario. I'll look into the problem, as it may be an easy fix, but out of curiosity: what kind of situation are you in whereby you want to start with both min/max at 0 ?

**Comment by JustinHawtree** [comment]
My application uses the slider to show the user how many times they want to do an action, but I dynamically show multiple sliders on different pages, so some might load with no available actions to pick from (if they exhausted all their actions). I could load the component with disabling the slider, but I didn't see a disabled option in the props documentation. I have max starting at -1 if it was 0, and it seems to work. But if you know how to disable the component I could go that route.

**Comment by simeydotme** [comment]
Good point about disabled state; I had overlooked that originally.

**Comment by simeydotme** [comment]
@JustinHawtree I've resovled teh `NaN` issue, and also added a `disabled` state in 1.7.0 :)

**Comment by JustinHawtree** [comment]
@simeydotme Thank you so much!
