### ISSUE TITLE
Issue When Adding a New Value to Values Array

### ISSUE THREAD

**Issue by cjriley9** [simeydotme/svelte-range-slider-pips#22]
I'm running into an issue when I push a new value to my values array. The thumb for my new value appears at the minimum value of the range slider, regardless of the value. You can grab the thumb and change the value, but the thumb itself doesn't move. 

Here is a link to a REPL instance where you can cause the error by hitting the "Add Break" button:
[Link](https://svelte.dev/repl/df2e00cc5baf4d68b1fa9e92024850c3?version=3.35.0)

I was able to fix this for my current use case by using a {#key} block and resetting the key any time I modify the array, here's an example:
[Link](https://svelte.dev/repl/c95284f138584ed9868cfb5ece26e0c8?version=3.35.0)

My fix doesn't seem very good, so built in support for this would be nice.

**Comment by simeydotme** [comment]
hmm, this looks weird! thanks for raising

**Comment by simeydotme** [comment]
hi @cjriley9 ...

I know it's been a while 😅  ... but I'm confident this issue is resolved in https://github.com/simeydotme/svelte-range-slider-pips/commit/6c13d5db47f6d2da84364b6d654cca505f9c9d11 which is now tagged as `1.8.1`.

thanks for your patience, and support! :)

**Comment by simeydotme** [comment]
your REPL; 
https://svelte.dev/repl/df2e00cc5baf4d68b1fa9e92024850c3?version=3.35.0
also works, now :)
