### ISSUE TITLE
Add ability to style pips better

### ISSUE THREAD

**Issue by simeydotme** [simeydotme/svelte-range-slider-pips#23]
cannot style pips with css if wanting to style each selected pip differently. 
add indexed css classes (`pip-selected--1`)

**Comment by zahachtah** [comment]
if you have multiple values, is it possible to style each handle differently, e.g. one red and one blue circle representing the handle fo different values?

**Comment by simeydotme** [comment]
hi @zahachtah 

please take a look at: 
https://codepen.io/simeydotme/pen/KKNJdbK

Basically it is, with CSS, but it's a little awkward.
So that's what this ticket is for, to address the issue. I've not gotten around to it yet, though, so maybe use the CSS for now.
