### ISSUE TITLE
How do you change the colors?

### ISSUE THREAD

**Issue by harshmandan** [simeydotme/svelte-range-slider-pips#25]
**Describe the bug**
I couldn't find any example of changing the colors.

**To Reproduce**
Here's a repl for the same.
https://svelte.dev/repl/8ff74f371b0b462c81fc71113924ce23?version=3.32.1

**Comment by harshmandan** [comment]
NVM. It works.
Had to use the global scope as it said in the Docs.
Here's the REPL link:
https://svelte.dev/repl/8ff74f371b0b462c81fc71113924ce23?version=3.32.1

**Comment by simeydotme** [comment]
Thanks @harshmandan  so much for providing a good example for others, after you figured it out 🙏 
<sub>_(and bonus thanks for reading the docs, and using the reduced test-case from contributing guide!!!)_</sub>
