### ISSUE TITLE
Add ability to control initial value before first user interaction.

### ISSUE THREAD

**Issue by janosh** [simeydotme/svelte-range-slider-pips#26]
Would be cool if the initial value could be specified explicitly or left undefined. This is useful for controlling whether a form should be submittable if the field is required and the user never touched the range slider.

**Comment by simeydotme** [comment]
Thanks @janosh for the suggestion,

I think that's something you can implement inside your application;
https://svelte.dev/repl/a90bdc0e1fb8440d92fd34e2acc13aea?version=3.32.1

:)

**Comment by janosh** [comment]
Sorry, I think I didn't make myself clear but thanks for the example! I didn't know about `<RangeSlider all="label" />` even though I was looking for that feature. Could you add that to the readme? Can submit a PR if you're busy.

**Comment by janosh** [comment]
Maybe you're right and it's a bad idea from UX perspective. The use case I was asking about is this signup form (scroll down a little to see the range slider and change the signup type with the top-most button to see another)

https://studenten-bilden-schueler.de/anmeldung

The form can be submitted either by tutors or tutees. For tutors, they can specify a class range for tutees they would like to teach. The default there is to assume all classes (1 - 13 in Germany). For tutees, it's a single slider (they only attend one level) and the default should be undefined cause we don't know what class level a student is currently attending. But the form should be non-submittable unless they touched the range slider to specify what class they're attending.

PR for `all='label'` incoming.
