### ISSUE TITLE
Styling prefix and suffix 

### ISSUE THREAD

**Issue by kauaicreative** [simeydotme/svelte-range-slider-pips#27]
Is there a way to style the prefix and suffix independently of the value?

**Comment by simeydotme** [comment]
currently, @kauaicreative ; no.

It could be added as a feature request, though.

**Comment by simeydotme** [comment]
hi @kauaicreative  there is now a nice way to style the prefix/suffix.
You may update to the newest version (1.8.0) and inspect the prefix/suffix for the css class.
