### ISSUE TITLE
Showing Even Labels

### ISSUE THREAD

**Issue by Abhi-ak** [simeydotme/svelte-range-slider-pips#31]
Hi, I am using this module in react project. The requirement is to show even years with label [2006,2008,2010.....2020] and odd years with just pips and no label. What is the prop/style config for this?

**Comment by Abhi-ak** [comment]
@simeydotme

**Comment by simeydotme** [comment]
## Admonishing;
@Abhi-ak  please read a github repo [Contributing.md](https://github.com/simeydotme/svelte-range-slider-pips/blob/main/CONTRIBUTING.md) before posting questions :) 

## Answer; 
Use CSS.
https://svelte.dev/repl/f7c2141a4d924ebc9aa03ae0fbe28c4e?version=3.32.1

**Comment by Abhi-ak** [comment]
Ya, I got it.. Thanks
