### ISSUE TITLE
Issue while running npm run build

### ISSUE THREAD

**Issue by Abhi-ak** [simeydotme/svelte-range-slider-pips#32]
Error Shown

`Name expected [../node_modules/svelte-range-slider-pips/dist/svelte-range-slider-pips.mjs:22,0]`

This is the import i used in my component:
`import RangeSlider from "svelte-range-slider-pips";`

What is the reason for this error and how to fix this ?

**Comment by Abhi-ak** [comment]
@simeydotme

**Comment by simeydotme** [comment]
Are you building a Svelte application, or something else _(like React, or Vue, or some non-component VanillaJS application)_?

**Comment by Abhi-ak** [comment]
hi @simeydotme fixed this by loading the package using cdn

**Comment by simeydotme** [comment]
may you share the before & after, plus your steps to resolve, for anyone else who suffer the same issue? :)
