### ISSUE TITLE
ValidationError when compiling

### ISSUE THREAD

**Issue by meygpons** [simeydotme/svelte-range-slider-pips#37]
Hi.

There is an error compiling the code. I think it's because of the new version of svelte. Yesterday the component was good for me and today it doesn't, the only change that has been made has been to update the version of svelte.

You could separate the :global in two?

```
ERROR in ./node_modules/svelte-range-slider-pips/src/RangeSlider.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: ValidationError: :global(...) must contain a single selector (570:2)
568:     transition: opacity 0.2s ease;
569:   }
570:   :global(.rangeSlider, .rangeSlider *) {
       ^
571:     user-select: none;
572:   }
```

https://github.com/simeydotme/svelte-range-slider-pips/blob/4c8fa3f1a594d48361c151d8ef17506da6685b5b/src/RangeSlider.svelte#L570

Thank you.

**Comment by evdama** [comment]
Yup, exact same error here as well... I upgraded to new svelte as well i.e. works with svelte v3.38.2 but fails with v3.38.3

**Comment by Shogoki** [comment]
+1 for this. Using latest svelte version breaks this

**Comment by simeydotme** [comment]
I've merged the fix, thanks for raising to my attention :) 
I will push to NPM as soon as I have a chance, thanks for your patience.
