### ISSUE TITLE
Click pip or label to select value

### ISSUE THREAD

**Issue by niclasmattsson** [simeydotme/svelte-range-slider-pips#38]
This is halfway between a bug report and feature request. Currently, clicking on pips or labels is the same as clicking on the actual slider at that pixel. This means that clicking on labels will often give inaccurate results for continuous sliders or sliders with small step values. Click the "30" label in this REPL example to see what I mean.
https://svelte.dev/repl/fefe88d5a0574258837318c9db46bc63?version=3

Depending on exactly where you clicked you might get any value between 28 and 32. I'd expect clicking on labels to set the slider to exactly that value. Then you'd have the best of both worlds: the free range of a continuous slider with some easy clickable shortcuts to set frequently used exact values (e.g. zoom to 50% and 100%).

For extra brownie points, highlight the labels on hover (see mockup in the REPL). Thanks for developing such a great component!

**Comment by simeydotme** [comment]
thanks @niclasmattsson for the raised issue and good description :)

It's actually something I implemented in the predecessor https://simeydotme.github.io/jQuery-ui-Slider-Pips/ and have been wondering whether it's necessary for this version. I held off until now to keep the LOC footprint low.

Let me have a look at how much it will impact and get back to you. In the mean-time, we can see if there's any +1's.

---

_One thing, though.
I can't justify adding the hover effect to the labels at this time as it'd warrant a "major" version update for what amounts to an aesthetic choice. And as you have shown, it's fairly trivial to implement by one's self. I'd put it in a backlog for v2._

**Comment by niclasmattsson** [comment]
Great, thanks. I think you'll find that Svelte makes the marginal LOC cost for extra features like this very low - fingers crossed at least. No worries about skipping the hover. I tweaked the CSS of my REPL example to get rid of the transition delay when hovering (but keeping it for the selected pip value). Just in case someone else finds it useful.

**Comment by simeydotme** [comment]
hi @niclasmattsson  ... I haven't published the NPM package yet, but please check out https://svelte.dev/repl/6bf5d88d6ece4ba9a26443e33c79f1c0?version=3.43.1 for an example of the changes. I haven't published them on NPM yet as I'm still debating the other change in the 2.0.0 milestone.

If you want to try out these changes, u may directly call 2.0.0 tag from github in your package.json

**Comment by niclasmattsson** [comment]
Wow, that looks perfect! Back in July I implemented an ugly workaround involving putting my own onclick-events on every `pipVal`, but this is so much cleaner. I'll keep an eye on your repo for the 2.0 release. Thank you!
