### ISSUE TITLE
[bug] Apparent no-reason glitch in slider among multiple ones

### ISSUE THREAD

**Issue by Pierstoval** [simeydotme/svelte-range-slider-pips#40]
**Describe the bug**
I have two sliders with float, pips and labels. One of them works perfectly, and the other one doesn't: it jiggles too much and sticks to the end franticly while you slide it, making it really hard to select a value.

**To Reproduce**

The project's repository: https://github.com/Pierstoval/handpan-svelte/
It is hosted on Github Pages there: https://pierstoval.github.io/handpan-svelte/

Move the "Speed (bpm)" slider to reproduce.

**Screenshots**

See:
![Animation](https://user-images.githubusercontent.com/3369266/127732029-8bf7eda4-f3cf-4323-9f8f-33d7b5805d09.gif)

**Device/Environment**

`svelte-range-slider-pips` version: `1.8.0`

Tested on Windows 10 Pro, with Firefox 90.0.2 and Brave 1.27.109 (uses Chromium: 92.0.4515.115).

**Additional context**

Here's the code: `<RangeSlider  min={Track.MIN_BPM} max={Track.MAX_BPM} step=5 float pips pipstep=2 all="label" />` (the `Track` class comes from the project's Typescript sources)

I have tried several solutions, like removing bound variables, changing min/max/step/pipstep, removing the other slider... None worked.

What am I doing wrong?

**Comment by simeydotme** [comment]
Hi Pierstoval, are you able to make a reduced test case for me, using the ["CONTRIBUTING.md"](https://github.com/simeydotme/svelte-range-slider-pips/blob/main/CONTRIBUTING.md) so we can isolate the behaviour out of your application?

**Comment by Pierstoval** [comment]
Hey @simeydotme , took me a while to make it work because REPL seems to bug on Firefox too, but here's the link: https://svelte.dev/repl/a486127936104e2a8e2bf8738b7979d2?version=3.41.0


For the record, I managed to find a quickfix that doesn't exactly do what I want, but removing `step=` and adapting the `pipstep` value manages to remove the glitch: https://svelte.dev/repl/a486127936104e2a8e2bf8738b7979d2?version=3.41.0 , that's fine for now, but one should be able to set a `step` value conjointedly with `pipstep`, alas the glitch prevents it.

Hope it somehow helps 🤞

**Comment by simeydotme** [comment]
Thanks for the details and the REPLs!
I'll see what I can do. Thanks for your patience!

**Comment by simeydotme** [comment]
Ok, already fixed it... haha... 😅 

so, you are using: `step=5 pipstep=2` which is passing the values through as strings. We need them to be `Float` or `Integer` values. Try changing to; `step="{5}" pipstep="{2}"` which seems to fix the issue here; https://svelte.dev/repl/7769ce1134ba413296d8b3e689a44fbe?version=3.41.0

I wonder if I should parse the inputs as `Float` 🤔

**Comment by Pierstoval** [comment]
> I wonder if I should parse the inputs as `Float` 🤔

I think you can detect it automatically and parse it if necessary, with `isNaN()` and `parseFloat()`, WDYT?
