### ISSUE TITLE
[bug] Incorrect handling of negative min\max\step values

### ISSUE THREAD

**Issue by kolmakova** [simeydotme/svelte-range-slider-pips#46]
Hi! First of all, thanks for this stylish and useful component!

Currently there's no any mention in the doc that `step` value can't be negative, but component allows to do it in some cases. This can result in incorrect slider behavior: 

1. With the `min: 0, max: 50, step: -1` props, slider doesn't move smoothly as if `step` was equal to 1, no any error in the console.
2. If `min: 0, max: 50, step: -1, pips: true`, slider does not render at all and throws `Uncaught RangeError: Invalid array length`

There's no any mention in the doc about `min` can't be bigger than `max`, too. At this case, slider renders, but handle can't be moved at all, no errors in the console.

**Expected behavior**

Implement functional with the proper usage of `max` < `min` and `step` < 0, or handle these cases properly and update the doc.

**Comment by simeydotme** [comment]
Hi, Thanks @kolmakova .
I appreciate your time to open an issue!

Please check the Contribution guidelines first. And then if you create some REPL which can demonstrate your issues and why you believe they are valid bugs we can discuss further :)
