### ISSUE TITLE
[question] How to change the Height of the Slider?

### ISSUE THREAD

**Issue by werto87** [simeydotme/svelte-range-slider-pips#48]
The slider looks a bit big for me. I tried to make it smaller with 
```
	:global(#slider .rangeSlider) {
            height: 10px !important;
	}
```
But it seams not to work. How to change the complete height of the element (scale it down)?

**Comment by simeydotme** [comment]
hi @werto87  ... sorry if it's not super clear. I wanted to add this in the Documenation for a while but didn't get around to it.
You can change the slider dimensions by changing the font-size, as the sizes are all set in `em` units.

```css
.rangeSlider { font-size: 10px; }
```

See this REPL for some examples; https://svelte.dev/repl/3729ab625a314e899ac3f03138d0053f?version=3.44.1

**Comment by werto87** [comment]
Works for me. Thank You!
