### ISSUE TITLE
movable interval

### ISSUE THREAD

**Issue by zahachtah** [simeydotme/svelte-range-slider-pips#5]
Hi, what a great piece of code :-) really useful!

Would it be possible to add the possibility to move an interval, i.e. not only moving one of the two endpoints, but dragging the line between the endpoints to move the entire range?

**Comment by simeydotme** [comment]
hi @zahachtah ... if I understand correctly you're asking about the ability to translate the range without affecting the size of it?  
It's definitely possible. There's some things to consider though. I may experiment with this a little, but no promises.

**Comment by zahachtah** [comment]
yep, @simeydotme , moving a range 1-5 to 3-8 by holding the line in between the points for example. Thanks for considering to look at it, I know open source is by fun and motivation so at your leisure :-)

**Comment by simeydotme** [comment]
ok @zahachtah after a lot of deliberation and failed prototypes, I am calling this one as a **⛔ Nope** for now.

The slider's functionality and code design was done in a way which enables clicking/touching anywhere on the slider, and to be keyboard accessible, these considerations make the current implementation very difficult to wedge in the range-translation feature as the touch/mouse interaction events don't care about the range element. 

While considering whether I want to do a large amount of work to get this possible, I had to factor in the usefulness of the functionality. I also looked at some other Component Libraries for both React and Svelte and failed to find many examples of range translation which led me to believe it's not widely used.

Thanks for your input, and please feel free to try yourself with a fork, and report back if you have something that doesn't deviate too much or introduce much regression :) 

Cheers, Simon

**Comment by zahachtah** [comment]
an example of your slider and a range-slider working side by side. No solution to the issue for svelte-range-slider--pips to implement this yet though. just FYI.

https://svelte.dev/repl/75d34e46cbe64bb68b7c2ac2c61931ce?version=3.34.0
