### ISSUE TITLE
[bug] <RangePips> was created with unknown prop 'orientationEnd'

### ISSUE THREAD

**Issue by wrex** [simeydotme/svelte-range-slider-pips#50]
Thanks for this rather awesome widget!

**Describe the bug**
I noticed a console message complaining about the unknown prop. Looking at the code it looks like `RangeSlider.svelte` passes `orientationEnd` to `RangePips.svelte` but that property is not defined.

**To Reproduce**

- ⛔ [The default REPL exhibits the bug](https://svelte.dev/repl/030797781fd64ad88302d1343f5b2c43?version=3.32.1) 

1. Visit the REPL above (unmodified)
2. Make the console larger to see the warning
3. See warning

**Expected behavior**

No console warning.

**Additional context**

This does not appear to cause any errors, but the console warning is slightly annoying. I'm unsure if you intended to use `orientationEnd` but wanted to ensure you're aware of the bug.

Since the bug manifests in the standard REPL, I've not included any screenshots or other environment info, but to be explicit I also see the error in the Chrome inspector console on a Mac with this line to instantiate a RangeSlider:

```html
<RangeSlider bind:values={$daysToReview} float pips {suffix} min={1} max={7} />
```

```js
$: suffix = $daysToReview[0] > 1 ? " days" : " day";
```

**Comment by simeydotme** [comment]
thanks, @wrex  ... I'll look in to this! :)

**Comment by wrex** [comment]
Bump.

Not sure what was intended, but commenting out the line with the `{orientationEnd}` prop being passed to the RangePips component in RangeSlider.svelte get rid of the console error anyway.

**Comment by simeydotme** [comment]
Yes Wrex, that's the solution. I originally thought I would need that passed to the pips with the other props in that commit; but I didn't. 

As I say I'll get around to this :) It's not a bug, just an extraneous piece of code which Svelte warns of in development environment. I'm not 100% certain, but I imagine this would be tree-shook out in prod builds, anyway.

If it's bothering you too much, send a PR 👍

**Comment by wrex** [comment]
Thanks! Just wanted confirmation that `orientationEnd` wasn't supposed to do something.
