### ISSUE TITLE
[docs] Trivial doc bug ("hoverable" not "hover")

### ISSUE THREAD

**Issue by wrex** [simeydotme/svelte-range-slider-pips#51]
**Describe the bug**
The table at https://simeydotme.github.io/svelte-range-slider-pips/#options describes an option for `hover` while the actual property name is `hoverable`. I think it's just a typo.

**Comment by simeydotme** [comment]
> Describe the bug
The table at https://simeydotme.github.io/svelte-range-slider-pips/#options describes an option for hover while the actual property name is hoverable. I think it's just a typo.

Thanks! I really need to spend more time on the demo/docs site :(
