### ISSUE TITLE
[bug] appears that Hoverable not working in REPL

### ISSUE THREAD

**Issue by simeydotme** [simeydotme/svelte-range-slider-pips#52]
> ~~ extracted from @wrex previous issue #51 

**Describe the bug**
When hovering with the default CSS variables I'm not seeing the float with the actual value, just the glow around the thumb. Once it's focused, the float appears but not when in hover state.

The doc example shows the float appearing on hover as I'd expect, but it's not appearing for some reason in my instance, despite `hoverable` being in its default state of `true`. Doubtless I'm doing something wrong, but I haven't figured it out yet.

EDIT: Actually, I just noticed the the REPL at https://svelte.dev/repl/030797781fd64ad88302d1343f5b2c43?version=3.32.1 exhibits the same behavior (just the glow around the thumb on hover without actually showing the value).

**Comment by simeydotme** [comment]
I just checked the REPL and compared to the documents site ... it looks like the REPL is somehow getting an old, or cached, version of the repo ... after explicitly setting the version to 1.8.0 it works; 

https://svelte.dev/repl/030797781fd64ad88302d1343f5b2c43?version=3.44.3

**Comment by wrex** [comment]
I've never done anything like that before in my life! (laugh)

This is an awesome component — saved me a ton of effort in a project I'm currently working on. Thanks!

**Comment by simeydotme** [comment]
resolved in `2.0.1` https://www.npmjs.com/package/svelte-range-slider-pips/v/2.0.1
Also updated the REPL to use latest version.

**Comment by wrex** [comment]
Much nicer. Thanks for the quick fix! 

And thanks for fixing my other minor annoyance with the unused prop — I'd actually meant to "bump" a trivial fix on another unrelated package that I **had** submitted a PR for!
