### ISSUE TITLE
help with import incantations to test svelte component using RangeSlider with jest

### ISSUE THREAD

**Issue by wrex** [simeydotme/svelte-range-slider-pips#53]
This is almost certainly due to my lack of understanding, but I've been having terrible difficulties trying to test my svelte components using RangeSlider in a node environment with jest. If you have any suggestions or advice, I'd love to hear them. If not, feel free to just close this issue.

My issue is with the (to my mind insane) amount of mystic transpiling required to use either of your published files (`.js` or `.mjs`) with jest/node.

My understanding:

- This project publishes two library files in the npm package:

    -  An IIFE: `./dist/svelte-range-slider-pips.js`
    - An ES6 module: `./dist/svelte-range-slider-pips.mjs`

- By default, jest [requires you to specify experimental options to node](https://jestjs.io/docs/ecmascript-modules) in order to use ECMAscript modules (apparently even with node 17).

With the NPM package installed, importing RangeSlider like this works fine in a browser environment:

```javascript
<script lang= "ts">
  import RangeSlider from "svelte-range-slider-pips";
  ...
</script>
```

But jest fails to run with `TypeError: RangeSlider is not a constructor`. My understanding is that this is because the distributed file is an IIFE and not a commonJS exported library/module.

So, next I tried the `.mjs` file per a hint from the documentation:

```javascript
<script lang= "ts">
  import RangeSlider from "../../node_modules/svelte-range-slider-pips/dist/svelte-range-slider-pips.mjs";
  ...
</script>
```

This at least generates a different error (`SyntaxError: Unexpected token 'export'`) and links to the jest documentation linked above.

If I try to run the tests per the jest documentation:

```
NODE_OPTIONS=--experimental-vm-modules npx jest src/components/SettingsForm.test.js
```

I get yet a different (but equally mystifying) error message:

```
Must use import to load ES Module: /Users/rex/Public/repos/ganbarometer-svelte/node_modules/svelte-range-slider-pips/dist/svelte-range-slider-pips.mjs
```

The only way I've been able to run tests successfully is to copy the `.svelte` files out of the `src/` subdirectory into my build tree directly. This works, and doesn't force me to make source changes from what works in the browser, but, of course, copying files out of `node_modules/` breaks `npm update` and forces me to manually copy again if a new version of the package is published.

None of this seems to be an issue with your code or flexible packaging decisions, but I'm pulling my hair out. I'm posting this in the desperate hope that you might have some advice. 

Front-end toolchain stuff hurts my head and breaks my spirit. All these incompatible environments and syntaxes seem bizarre to my "old-school" back-end sensibilities: I've got rollup using at least three different compilers/transpilers on the same source files: svelte, tsc, and babel.  Then there's commonJS and ES6 syntax in addition to typescript.  Of course I have to consider node vs. browser environments. Oh, did I mention my project needs to be published as a TamperMonkey userscript (IIFE)? How does anyone stay sane?!

**Comment by simeydotme** [comment]
> Front-end toolchain stuff hurts my head and breaks my spirit.

Yes, me too.. and I'm a pure frontend dev, lol.

I recently had to figure out something similar on another module I maintain (sparticles) where a user had warnings from VITE (another bundler) that my component was not a valid mjs module. https://github.com/simeydotme/sparticles/commit/313a6d2646b67a06556b01038834aae2c015ace2#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519 based on the issue; https://github.com/simeydotme/sparticles/issues/16 . 

The solution was to modify the package.json to make the `.mjs` file as the `main` and move the `.js` to one of the `files[]` ... I am not familiar with Jest or doing UI tests really so I can't help there. But maybe you can try forking the project and modifying the `package.json` as shown above and see if that helps? If it does, then we can try applying it back to this repo after I do some safeguarding and checks.

Good luck!

**Comment by wrex** [comment]
Thanks for the thoughtful reply! I'm making headway at the moment just instantiating the svelte file directly (broken as that is). I'll investigate further when I'm able.

I tried hiding the `.js` file altogether as an experiment so it could only see the module. It saw the `.mjs` file but still gave me errors.

I'll post back if I ever figure out how to beat it into submission. 

There are few things more annoying than having tool-chain issues break your unit tests!

**Comment by simeydotme** [comment]
> I'll post back if I ever figure out how to beat it into submission.

Thanks, and if you figure out it can be added to the wiki for others to find :)
