### ISSUE TITLE
[bug] Clicking on a pip while slide is disabled moves the handle

### ISSUE THREAD

**Issue by gbcreation** [simeydotme/svelte-range-slider-pips#57]
**Describe the bug**

The handle of a disabled slider moves when clicking on pips.

**To Reproduce**

1. Use [this REPL ](https://svelte.dev/repl/5b0cbf7f7ba94cb3b760bcf970a7ab2a?version=3.32.1)
2. Click on one of he pips.

**Expected behavior**

The handle should not move when clicking on pips.

**Comment by simeydotme** [comment]
Oh nice, thanks for this!
