### ISSUE TITLE
[bug] 'selected' CSS property not working properly with float steps

### ISSUE THREAD

**Issue by wintermute-cell** [simeydotme/svelte-range-slider-pips#58]
**Description:**  
When using a step size of 0.05, and setting min/max to 0/1 respectively, the pips do not consistently get the 'selected' property applied.
This seems to have to do with their values suffering from floating point inaccuracies (0.6000000003 instead of 0.6).

**Reproduced in REPL:**
https://svelte.dev/repl/d5a08fc50b3d4f6cb23423be7fdbb976?version=3.46.4

1. Move the Slider.
2. Observe the label, only shown on the 'selected' pip.
3. Alternatively, use Browser Inspection Tool to check CSS properties.

**Expected behavior:**
The selected pip should get the 'selected' property.

**Possible Fix:**
Determine 'selected' pip by choosing nearest one to the actual value, or allow deviation instead of checking for exact equality.

**Comment by wintermute-cell** [comment]
Actual suggestion for a fix:
In `RangePips.svelte`:
Exchange line 43
```
return values.some(v => v === val);
```
with
```
return values.some(v => Math.abs(v - val) < 0.0001);
```

to check if the difference is within an allowed range (a deviation of 0.0001 in this case).

I don't have the time to do a proper pull request atm, will do so if it's not fixed when I find time though :)

**Comment by simeydotme** [comment]
Hey @wintermute-cell 

thanks for the detailed issue report!
this is a funny one, and I think you're right regarding floating point values!

I'm dubious about your suggestion, but this should be a relatively simple fix. I'll cover this shortly.

In the mean-time for a workaround you should be able to use whole integer values, and use the "formatter" function to display floats, if you wish.
