### ISSUE TITLE
[bug] Svelte warns about a missing `slider` prop

### ISSUE THREAD

**Issue by gbcreation** [simeydotme/svelte-range-slider-pips#59]
**Describe the bug**

When an instance of the RangeSlider is created without specifying the `slider` prop, Svelte displays the following warning in the JavaScript console : `<RangeSlider> was created without expected prop 'slider'`.

**To Reproduce**

- [Go to this REPL and open the Console at the bottom right](https://svelte.dev/repl/030797781fd64ad88302d1343f5b2c43?version=3.32.1)

**Expected behavior**

As the `slider` prop is not mandatory, there should be no warning.

**Possible solution**

Set the `slider` prop to `undefined` by default?

```javascript
// dom references
export let slider = undefined;
```

**Comment by simeydotme** [comment]
ah, thanks! :)
