### ISSUE TITLE
[feature] type support

### ISSUE THREAD

**Issue by ghostdevv** [simeydotme/svelte-range-slider-pips#65]
Currently there are no types shipped with the package, would be nice to do this

**Comment by ghostdevv** [comment]
In terms of options to auto generate types, you can either stick with the current rollup build system and use `sveld` to generate types. Or you can switch to sveltekit package and use that to build the package

**Comment by i7N3** [comment]
https://www.npmjs.com/package/@types/svelte-range-slider-pips

**Comment by simeydotme** [comment]
> I've created a type definition. You can add it as dev dep. https://www.npmjs.com/package/@types/svelte-range-slider-pips

Thanks @i7N3 ... is this a normal/accepted way to handle the issue? And if so is the issue closable? Or should the types be defined inside the repo?

**Comment by i7N3** [comment]
> > I've created a type definition. You can add it as dev dep. https://www.npmjs.com/package/@types/svelte-range-slider-pips
> 
> Thanks @i7N3 ... is this a normal/accepted way to handle the issue? And if so is the issue closable? Or should the types be defined inside the repo?

- Yes, if a package does not bundle its own types.
- Yes.
- [When a package bundles its own types, types should be removed from Definitely Typed to avoid confusion.](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package)

As someone mentioned here, there is a better way to rewrite svelte-range-slider-pips to typescript.

**Comment by simeydotme** [comment]
alright nerds, u got types in there now ;)
https://github.com/simeydotme/svelte-range-slider-pips/tree/3.1.0/dist/svelte/components
