### ISSUE TITLE
How can I turn off the spring animation completely?

### ISSUE THREAD

**Issue by rchrdnsh** [simeydotme/svelte-range-slider-pips#7]
It's quite distracting and not what I am personally looking for...How would I go about disabling the spring animation?

**Comment by rchrdnsh** [comment]
For anybody wondering in the future, I did this:

```html
<RangeSlider range="min" values={[50]} float springValues={{stiffness: 1, damping: 1}}/>
```

**Comment by simeydotme** [comment]
Thanks for leaving the answer!

**Comment by TJKoury** [comment]
This doesn't seem to work for me, it still bounces erratically.

**Comment by simeydotme** [comment]
> This doesn't seem to work for me, it still bounces erratically.

@TJKoury  could you provide a REPL for demo purposes?
