### ISSUE TITLE
[feature] Custom position and naming of pips

### ISSUE THREAD

**Issue by dtsmarin** [simeydotme/svelte-range-slider-pips#78]
I want to change the position of the pips similar to this example but also set custom names for them from JSON.
https://svelte.dev/repl/d777b85ba4c9493a8169676adbab1fa6?version=3.44.1

I also don't want the "snapping" of the pips is there a way to disable it? I only need the pips as a guide.

https://svelte.dev/repl/779c2b76db9a4d179f050b7c599fc874?version=3.49.0

I'll use the Range Slider component inside an each loop so I want to change the pips depending on the data.

**Comment by simeydotme** [comment]
> I also don't want the "snapping" of the pips is there a way to disable it? I only need the pips as a guide.

You can set the `step` to `1` (or the lowest increment you want) and the `pipstep` to whatever you want the pip scale to be. 

---

> I want to change the position of the pips similar to this example but also set custom names for them from JSON.

Good luck with that
