### ISSUE TITLE
Svelte 3.51.0+ reports missing `on:keyup`

### ISSUE THREAD

**Issue by janosh** [simeydotme/svelte-range-slider-pips#83]
Since updating to [Svelte 3.51.0](https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#3510) I'm getting tons of console warnings about missing `on:keyup` in `svelte-range-slider-pips` when starting up the dev server:

> 3:18:23 PM [vite-plugin-svelte] node_modules/svelte-range-slider-pips/src/RangePips.svelte:178:4 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
3:18:23 PM [vite-plugin-svelte] node_modules/svelte-range-slider-pips/src/RangePips.svelte:197:8 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
3:18:23 PM [vite-plugin-svelte] node_modules/svelte-range-slider-pips/src/RangePips.svelte:216:4 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event

**Comment by simeydotme** [comment]
thanks, @janosh  .... looks like a bug with Svelte Core, as the pips have no business being keyboard accessible. There may be another way to manage this instead of adding random keyup events to something that is not keyboard accessible :/

**Comment by janosh** [comment]
Do you think it makes sense to add a `tabindex` to _make_ the pips keyboard accessible?

**Comment by simeydotme** [comment]
no, totally not, as the slider "knobs" are keyboard accessible and can be moved using arrows, home, end, etc. That's following the guide from the WAI range slider ARIA guidelines https://www.w3.org/WAI/ARIA/apg/patterns/slider/ 

I do realise that the pips (range numbers) are an additional feature and not documented (the whole point of this plugin), however I strongly feel like the usability will be diminished by making the pips/numbers focusable

**Comment by janosh** [comment]
@simeydotme In that case, how about changing the nodes from `<span>` to `<button>`?
