### ISSUE TITLE
[feature] Support for non-linear ranges

### ISSUE THREAD

**Issue by FlyingDR** [simeydotme/svelte-range-slider-pips#86]
**Describe the feature**
It would be great to have support for non-linear ranges for the slider. 

**Explain it's value / reasoning**
At this moment slider splits the given range into equal parts, but sometimes a non-linear (e.g. logarithmic or even custom) scale is required. 

For example, in our project we have a range of fixed values that starts with 1,2,3,5,8 ... and ends with 1000, 2000, 3000, 5000, 10000, 15000. Of course, putting them on a linear scale is not practical because it will be hard to select values at either start or end of the range depending on the chosen scale.

**Additional context**
A living example of support for non-linear sliders can be seen [here](https://refreshless.com/nouislider/slider-values/#section-non-linear) as part of the documentation of the [`noUiSlider`](https://refreshless.com/nouislider/)

**Comment by simeydotme** [comment]
Hi @FlyingDR ,

Thanks, but I do not plan to add support for super custom pip placement and snapping. It would add significant complexity and probably bundle size.

I wonder what your desired UX is, though? Because depending on how many steps you have, and how you want it "feel", this  may be useful to you; https://svelte.dev/repl/d777b85ba4c9493a8169676adbab1fa6?version=3.44.1 ... or if you can draw out a simple example of what you need we might be able to figure it out :)

If not, then maybe you can consider converting to noUISlider ... it's not too dissimilar in bundle size :)

**Comment by FlyingDR** [comment]
@simeydotme This is an incredibly great example, really appreciate it!

However, as I wrote before - we have a range of values that spans from zero to several thousand. In this case, the proposed solution does not work well. 

[Please take a look](https://svelte.dev/repl/1abf91c283154181a9410a4de81fb0c8?version=3.44.1), these values are more or less represent the real range. As you can see - on the left there is very hard to select some particular value while on the right there is a very large gap between subsequent values.

My thought was to have the ability to have some kind of mapping between actual values and their positions on the slider, e.g. a function that accepts a value and returns its relative (`0..1`) position and vice versa.

**Comment by simeydotme** [comment]
> My thought was to have the ability to have some kind of mapping between actual values and their positions on the slider, e.g. a function that accepts a value and returns its relative (0..1) position and vice versa.

forgive me, but may I state something... isn't this technically just radio-list at this point?

And also, is not possible for you to map? 
https://svelte.dev/repl/bd74fe0f45c04a2f95001c7624703d5b?version=3.44.1 something like this?
I know it's not an logarithmic scale, it's just an evenly placed set of values and each stop represents an index in the lookup table, but it's the best I can do. The code is not written in a way that can support arbitrary placements of stops.

**Comment by FlyingDR** [comment]
@simeydotme This is exactly what we also end up with from our side. Thank you once again!

I'll close the issue if you don't mind, hope that REPL links will be useful for other people who may look for something similar. 

It may be worth adding the last REPL in [documentation](https://simeydotme.github.io/svelte-range-slider-pips/) as an example of how such cases may be solved.
