### ISSUE TITLE
[bug] Module can only be default-imported using the 'allowSyntheticDefaultImports' flag

### ISSUE THREAD

**Issue by probablykasper** [simeydotme/svelte-range-slider-pips#89]
**Describe the bug**

I'm seeing this lint error when importing RangeSlider:
```
Error: Module '"/Users/k/dev/git/limey/node_modules/@types/svelte-range-slider-pips/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag (ts)
<script lang="ts">
  import RangeSlider from 'svelte-range-slider-pips'
```

**To Reproduce**

1. `npm create svelte@latest my-app`
2. Create a skeleton project with TypeScript syntax
3. `npm i -D svelte-range-slider-pips @types/svelte-range-slider-pips`
4. Use the following code:
    ```svelte
    <script lang='ts'>
      import RangeSlider from 'svelte-range-slider-pips'
    </script>
    ```

**Comment by jfrancos** [comment]
Instead of using `create svelte` try starting the project with `create vite` -- follow the prompts for setting up svelte and typescript:
```
npm create vite@latest
```
https://vitejs.dev/guide/#scaffolding-your-first-vite-project

**Comment by probablykasper** [comment]
Thanks, that does seem to work!
