### ISSUE TITLE
Feature Request: Custom PIPS Positions...

### ISSUE THREAD

**Issue by rchrdnsh** [simeydotme/svelte-range-slider-pips#9]
The PIPS seem to only be able to be even distributed, but I would like the ability to timestamp the slider at specific points. The use case would be an audio or video slider where I can mark where the Chorus happens, for example, like so:

![song-slider-example](https://user-images.githubusercontent.com/7884263/98857312-c0a5c500-2413-11eb-9733-55248c057b4e.png)

...it would also be cool for people to be able to click on the song position dots and jump right to that point in the music as well :-)

**Comment by simeydotme** [comment]
Hi @rchrdnsh  ...

I'm a little worried about how you're using the slider, haha, as it's definitely not expected to use as a timeline...

with that being said... actually the pips/labels are all accessible with CSS, so in theory if you had a easily divisible number of pips (something like 100, 200, 500, etc) you could then use some clever css to hide all pips, but show pip 233 for example by settings;

```css
.rangePips .pip {
  display: none;
}
.rangePips .pip:nth-child(233) {
  display: block;
}
```

this may, or may not, be possible in your application ...

you may also be able to use `formatter()` method to determine the pip# and add a label to it, while hiding the actual pips with CSS

Both are a little hacky, but I do not plan to support arbitrary placement of pips except using the steps / formatters :)

**Comment by rchrdnsh** [comment]
Hi @simeydotme, thanks for the quick reply :-)

hmmmm...what do you think would need to be different/added for this to function as a progress bar/timeline as well?

the <progress/> element alone doesn't cut it for me, and the <input type='range'> alone doesn't cut it for me either, been down those roads for too long now...

I need the functionality of both in one...

so, what would need to change for this component (or something like it) to support <progress/> like capabilities, in your opinion?
