### ISSUE TITLE
[bug] with touch events, handle moves back to initially-pressed location

### ISSUE THREAD

**Issue by jfrancos** [simeydotme/svelte-range-slider-pips#90]
**Describe the bug**
On mobile (i.e. with touch events) if you press on a part of the slider, then drag, then let go, once you let go it jumps back to the initial place where you pressed.  This behavior doesn't occur when using the mouse cursor.

**To Reproduce**
1. Go to the [Svelte component demo](https://svelte.dev/repl/030797781fd64ad88302d1343f5b2c43?version=3)
2. Open the browser's JS console
3. Click the mobile-device icon in the upper-left hand corner of the js console
4. Click on a part of the slider to the left or right from where the handle currently is -- seems to be most noticeable when you click on a nib, just below the slider (the bug doesn't seem to happen if you click just above the slider)
5. Drag the handle a bit to the left or right
6. Release the mouse.  The handle will slide back to where the initial click was

**Expected behavior**
I expect the behavior to be the same as when using a mouse cursor, where the handle stays where it is once released.  The behavior seems to be correct for the 1.x versions, and incorrect (as above) for the 2.x versions.

**Screenshots**
https://user-images.githubusercontent.com/14883673/206074573-6c4a4803-8b3d-42f3-a593-4a39b140ed75.mov

**Device/Environtment**
Chrome with mobile simulation

**Comment by jfrancos** [comment]
I'm able to work around this in my own code with `id="rs"` and
```
:global(#rs.rangeSlider > .rangePips) {
  pointer-events: none;
}
```

**Comment by simeydotme** [comment]
thanks @jfrancos , I'll take a look :)

**Comment by simeydotme** [comment]
should be resolved as of latest version :)
