### ISSUE TITLE
[feature] Lock values to a range

### ISSUE THREAD

**Issue by henryjameslau** [simeydotme/svelte-range-slider-pips#96]
**Describe the feature**
I have slider using the range mode and I want to be able to set a handle to not go past a specific point. If this was not a range I'd be able to use `min` but since this is a range I cannot. 

**Explain it's value / reasoning**
I'm using a slider to filter an array of numbers and I need at least two numbers between the min and max set by the slider. In this particular example I'm calculating equal interval breaks which needs more than one number to do the calculations. 

**Additional context**
Here an image of the slider in use.
![image](https://user-images.githubusercontent.com/2945099/220342457-afa54298-02d0-4591-9131-534195e85ec8.png)

**Comment by simeydotme** [comment]
Hi @henryjameslau .. I don't fully understand your description, is it like this?;

```
|---------◉------------------------◉--------------|
0    1    2    3    4    5    6    7    8    9    10
```
You want to block the left-thumb from going past the number 2? like a fake "min" ?

If that's the case, you can add this yourself with the `on:start`, `on:change`, or `on:end` events https://github.com/simeydotme/svelte-range-slider-pips#slider-events-dispatched and detect if the value is less than your desired "min" and then re-set the value to the min value.

**Comment by simeydotme** [comment]
you could also generate a "fake" disabled slider, and position it behind the actual slider to appear like they are the the same :)
